# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('borrow_request', 'Borrow Request'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('book_handed_over', 'Book Handed Over'), ('return_confirmed', 'Return Confirmed'), ('new_message', 'New Message'), ('extension_request', 'Extension Request'), ('overdue_warning', 'Overdue Warning'), ('rating_received', 'Rating Received'), ('report_resolved', 'Report Resolved'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
