# Generated by Django 5.2.13 on 2026-04-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
