# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('language', models.CharField(default='English', max_length=50)),
                ('material_type', models.CharField(choices=[('book', 'Book'), ('notes', 'Notes'), ('pdf', 'PDF'), ('magazine', 'Magazine'), ('textbook', 'Textbook'), ('other', 'Other')], default='book', max_length=20)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('availability_type', models.CharField(choices=[('borrow', 'Available to Borrow'), ('donate', 'Donation'), ('exchange', 'Exchange Only')], default='borrow', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('borrowed', 'Currently Borrowed'), ('reserved', 'Reserved'), ('donated', 'Donated'), ('inactive', 'Inactive'), ('removed', 'Removed by Admin')], default='active', max_length=20)),
                ('max_borrow_days', models.PositiveSmallIntegerField(default=14)),
                ('is_free', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pickup_instructions', models.TextField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('digital_only', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='books/qr_codes/')),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='books/images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'book_images',
                'ordering': ['order', '-is_cover'],
            },
        ),
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake', 'Fake Listing'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('already_gone', 'Book No Longer Available'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'book_reports',
            },
        ),
        migrations.CreateModel(
            name='SavedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saved_books',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-usage_count'],
            },
        ),
    ]
