# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='books.book'),
        ),
        migrations.AddField(
            model_name='savedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreport',
            unique_together={('reporter', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='savedbook',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_title_7a737c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['subject'], name='books_subject_ef900a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_status_08b8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['city'], name='books_city_e312c0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['availability_type'], name='books_availab_e01ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['latitude', 'longitude'], name='books_latitud_c6f17e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_created_9e859d_idx'),
        ),
    ]
