# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active (Book Handed Over)'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('requested_duration_days', models.PositiveSmallIntegerField(default=14)),
                ('actual_duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extension_requested', models.BooleanField(default=False)),
                ('extension_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extension_approved', models.BooleanField(null=True)),
                ('borrower_note', models.TextField(blank=True, max_length=500)),
                ('rejection_reason', models.TextField(blank=True, max_length=500)),
                ('handover_code', models.CharField(blank=True, max_length=8)),
                ('return_code', models.CharField(blank=True, max_length=8)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_days', models.PositiveSmallIntegerField(default=0)),
                ('late_return_warned', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.book')),
            ],
            options={
                'db_table': 'borrow_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
