# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['borrower', 'status'], name='borrow_requ_borrowe_c44dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['lender', 'status'], name='borrow_requ_lender__fa935a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['book', 'status'], name='borrow_requ_book_id_651926_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['due_date'], name='borrow_requ_due_dat_ac8e53_idx'),
        ),
    ]
